pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('deploy'){
            steps{
                echo "deploying"
                sh 'scp /var/lib/jenkins/.m2/repository/pds/smartus/front-end/0.0.1-SNAPSHOT/front-end-0.0.1-SNAPSHOT.jar toto@172.31.249.231:/tmp'
                sh 'ssh toto@172.31.249.231 /opt/prod/scripts/update-jar.sh'
            }
        }
    }   
}
